default: &default
  adapter: postgresql
  encoding: unicode
  user: dannybenshi
  password: DannyPro123
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_react_rails_development

test:
  <<: *default
  database: hello_react_rails_test

production:
  <<: *default
  database: Hello_React_on_Rails_production
  username: Hello_React_on_Rails
  password: <%= ENV["HELLO_REACT_ON_RAILS_DATABASE_PASSWORD"] %>
